%% foefyp.cls Jan 03 2020 version 1.0
%%
%% This is the unofficial MMU thesis LaTeX class for undergraduate
%% students of Multimedia University, Cyberjaya. It is created
%% according to http://foe.mmu.edu.my/v3/main/undergrad/fyp_report_guidelines.html
%%
%% Made by Chia Jason and Chai Yee Ting
%% maintainer: Chia Jason (chia_jason96@live.com)

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{mmuthesis}[LaTeX2e class for MMU FoE FYP Thesis v1.0. Copyright (c) 2020 Chia Jason and Chai Yee Ting (chia_jason96@live.com)]
